image: k33g/procyon-ng:0.0.0

tasks:
  - name: initialize
    before: |

      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env
      wasmedge --version

    init: |
      echo "🚀 initialize"
      cd js-node npm install
      cd ..
      clear
      export DOTNET_ROOT=$HOME/dotnet
      export PATH=$PATH:$HOME/dotnet
      dotnet --version

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 4000
    visibility: public

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - rust-lang.rust
    - bungcip.better-toml
    - aaron-bond.better-comments
    - grain-lang.vscode-grain
